export const ERROR_CODES = {
  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  INVALID_SIGNATURE: 'INVALID_SIGNATURE',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USERNAME_TAKEN: 'USERNAME_TAKEN',
  EMAIL_TAKEN: 'EMAIL_TAKEN',
  WALLET_TAKEN: 'WALLET_TAKEN',
  USER_BANNED: 'USER_BANNED',

  // Chat
  CHAT_NOT_FOUND: 'CHAT_NOT_FOUND',
  NOT_CHAT_MEMBER: 'NOT_CHAT_MEMBER',
  ALREADY_MEMBER: 'ALREADY_MEMBER',
  GROUP_FULL: 'GROUP_FULL',
  INVALID_INVITE: 'INVALID_INVITE',

  // Message
  MESSAGE_NOT_FOUND: 'MESSAGE_NOT_FOUND',
  MESSAGE_TOO_LONG: 'MESSAGE_TOO_LONG',

  // File
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',

  // General
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
} as const;
